package cli

import (
	"errors"
	"fmt"
	"os/exec"
	"os/user"
	"strings"

	"github.com/spf13/cobra"
)

// sudoersFile is where the generated snippet is meant to live. sudo ignores
// files in /etc/sudoers.d whose name contains a dot or ends with '~', so the
// name deliberately has no extension.
const sudoersFile = "/etc/sudoers.d/klimax"

func newSudoersCmd() *cobra.Command {
	var check bool
	cmd := &cobra.Command{
		Use:   "sudoers",
		Short: "Print a sudoers snippet so 'klimax up' can manage the host route without a password",
		Long: `klimax needs root only to add or refresh one macOS route: the kind bridge CIDR
via the VM's lima0 IP. This prints a sudoers snippet granting exactly those two
route commands, so 'klimax up' never prompts for a password — which is also what
makes 'klimax autostart' work at login.

Install it with:

  klimax sudoers | sudo tee ` + sudoersFile + ` >/dev/null
  sudo chmod 0440 ` + sudoersFile + `
  sudo visudo -c -f ` + sudoersFile + `      # verify syntax

The rules are scoped to the configured CIDR: they permit creating and deleting a
route for that subnet only, with any gateway (the lima0 IP is assigned by macOS
and changes across VM restarts).

--check inspects the sudo policy for the two NOPASSWD rules, rather than trying
the commands (which a cached sudo credential would let through regardless).`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if check {
				return runSudoersCheck()
			}
			return runSudoers()
		},
	}
	cmd.Flags().BoolVar(&check, "check", false, "Check whether the route commands already run without a password")
	return cmd
}

// sudoersSnippet renders the sudoers rules for the given user and CIDR. The two
// commands must stay in sync with routing.EnsureRoute / routing.DeleteRoute.
func sudoersSnippet(username, cidr string) string {
	return fmt.Sprintf(`# klimax — passwordless management of the macOS route for the kind bridge CIDR.
# Generated by 'klimax sudoers'. Regenerate after changing network.kindBridgeCIDR.
#
# Scope: creating or deleting a route for %s only. The trailing wildcard is the
# gateway (the VM's lima0 IP), which macOS assigns dynamically.
%s ALL=(root) NOPASSWD: /sbin/route -n add -net %s *
%s ALL=(root) NOPASSWD: /sbin/route -n delete -net %s
`, cidr, username, cidr, username, cidr)
}

func runSudoers() error {
	cfg, err := loadAndValidate()
	if err != nil {
		return err
	}
	u, err := user.Current()
	if err != nil {
		return fmt.Errorf("resolving current user: %w", err)
	}
	fmt.Print(sudoersSnippet(u.Username, cfg.Network.KindBridgeCIDR))
	return nil
}

func runSudoersCheck() error {
	cfg, err := loadAndValidate()
	if err != nil {
		return err
	}
	cidr := cfg.Network.KindBridgeCIDR

	// Read the policy rather than trying the commands: with a cached sudo
	// credential, an admin user can run anything, so a successful trial run would
	// prove nothing about the rules being installed.
	out, err := exec.Command("sudo", "-n", "-l").CombinedOutput()
	if err != nil {
		fmt.Printf("? Could not read the sudo policy without a password.\n")
		fmt.Printf("  Verify manually:  sudo -l | grep '/sbin/route'\n")
		return errors.New("could not determine whether the klimax sudoers rules are installed")
	}

	hasAdd, hasDel := findRouteRules(string(out), cidr)
	if hasAdd && hasDel {
		fmt.Printf("✓ Passwordless route rules for %s are in effect.\n", cidr)
		return nil
	}

	fmt.Printf("✗ The passwordless route rules for %s are not installed", cidr)
	switch {
	case hasAdd && !hasDel:
		fmt.Printf(" (found the 'add' rule, missing 'delete')")
	case !hasAdd && hasDel:
		fmt.Printf(" (found the 'delete' rule, missing 'add')")
	}
	fmt.Printf(".\n\nInstall them:\n  klimax sudoers | sudo tee %s >/dev/null\n  sudo chmod 0440 %s\n",
		sudoersFile, sudoersFile)
	return fmt.Errorf("sudoers rules for %s are not in effect", cidr)
}

// findRouteRules scans `sudo -l` output for NOPASSWD rules covering the route
// add and delete commands for cidr.
func findRouteRules(sudoList, cidr string) (hasAdd, hasDel bool) {
	for _, line := range strings.Split(sudoList, "\n") {
		if !strings.Contains(line, "NOPASSWD") || !strings.Contains(line, "/sbin/route") || !strings.Contains(line, cidr) {
			continue
		}
		if strings.Contains(line, " add ") {
			hasAdd = true
		}
		if strings.Contains(line, " delete ") {
			hasDel = true
		}
	}
	return hasAdd, hasDel
}
